repos:
  - repo: local
    hooks:
      - id: deptry
        name: deptry
        entry: uv run --directory core deptry .
        language: system
        pass_filenames: false
        files: ^core/


